version: '3'
services:
  db:
    image: mysql:8.0.21
    environment:
      MYSQL_ROOT_PASSWORD: Tgkwtkm_0
      MYSQL_DATABASE: share_ramen_app_development
    ports:
      - "4306:3306"
    volumes:
      - ./mysql-confd:/etc/mysql/conf.d
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/share_ramen_app
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  mysql-data:
